# Generated by Django 5.1.5 on 2025-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('metier', models.CharField(choices=[('APD', 'APD'), ('DBE', 'DBE'), ('ASSC', 'ASSC')], max_length=100)),
                ('Ages', models.IntegerField()),
                ('est_inscris', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
